synthesize_guide_task:
  description: >
    Take the user's query: `{topic}` and the list of retrieved documents,
    rerank them for relevance, and then synthesize a clear, step-by-step guide.
  expected_output: >
    A clear, step-by-step guide based on the most relevant retrieved information.

report_generation_task:
  description: >
    Take the provided step-by-step guide and transform it into a final, user-friendly report.
    - Your primary input is the result of the synthesize_guide_task.
    - Format the entire output using Markdown for excellent readability. Use headings, bullet points, numbered lists, and bold text to structure the information clearly.
    - If you encounter an `[image_info]` tag in the text, replace it with a clear instruction for the user interface. For example, if you see `[image_info]{"description": "A chart showing Q3 sales.", "imgpath": "/path/to/image.png"}[/image_info]`, you should output:
      "---
      **Image:** A chart showing Q3 sales. (Path: /path/to/image.png)
      ---"
    - Ensure the final report is well-organized, professional, and directly addresses the original user query: `{topic}`.
  expected_output: >
    A polished, comprehensive, and easy-to-read report in Markdown format.
    The report should be fully formatted and include clear placeholders for any images referenced in the source guide.