synthesize_guide_task:
  description: >
    Take the user's query: `{topic}` and the list of retrieved documents: {documents},
    and then synthesize a clear, step-by-step guide.
    - You MUST preserve any `[image_info]` tags that contain valid, non-empty JSON content.
    - If a document does NOT contain any `[image_info]` tags, or if a tag is empty or malformed,
      you MUST NOT include any `[image_info]` tag in your output.
    - Do not invent or create any new image tags.
  expected_output: >
    A clear, step-by-step guide based on the most relevant retrieved information.
    This guide should ONLY include `[image_info]` tags if they were valid and present in the source documents.

report_generation_task:
  description: >
    Take the provided step-by-step guide and transform it into a final, user-friendly report.
    - Your primary input is the result of the synthesize_guide_task.
    - Format the entire output using Markdown for excellent readability.
    - You MUST ONLY process `[image_info]` tags if they are explicitly present in the input and contain valid JSON.
    - For example, if a valid tag `[image_info]{"description": "A real chart.", "imgpath": "/path/to/real_image.png"}[/image_info]` exists, reformat it as:
      "---
      **Image:** A real chart. (Path: /path/to/real_image.png)
      ---"
    - If there are NO `[image_info]` tags in the input, or if any tag is empty or malformed,
      you MUST NOT create, invent, or hallucinate any image references. Do not use the example text.
    - Ensure the final report is well-organized, professional, and directly addresses the original user query: `{topic}`.
  expected_output: >
    A polished, comprehensive, and easy-to-read report in Markdown format.
    The report must not contain any image references unless they were explicitly provided with valid data in the input guide.
